/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myapplication_mask_com_myapplication_MainActivity */

#ifndef _Included_myapplication_mask_com_myapplication_MainActivity
#define _Included_myapplication_mask_com_myapplication_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myapplication_mask_com_myapplication_MainActivity
 * Method:    FromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_myapplication_mask_com_myapplication_MainActivity_FromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
